version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - type: "all"
        dependency-name: "*"
        dependency-type: "all"
        update-type: "all"
