name: CI/CD

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: node:18-alpine

    steps:
    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
  test:
    runs-on: ubuntu-latest

    container:
      image: node:18-alpine

    steps:
    - name: Install dependencies
      run: npm install

    - name: Test
      run: npm run test
